wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1722329428
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 23
      4: 3.12.4
      5: 0.17.5
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
