#compose.yaml
services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000' #8000번 포트를 컨테이너의 8000번 포트와 연결
    restart: "no"  #컨테이너가 종료되었을 때 자동으로 재시작하지 않도록 설정